import Landing from "@/components/Landing";
import Materials from "@/components/Materials";
import CartContextProvider from "@/helpers/cartContext";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>CoolCode Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CartContextProvider>
          <Landing />
          <Materials />
        </CartContextProvider>
      </main>
    </>
  );
}
